### ISSUE TITLE
not uploading on a WisBlock Core RAK4631 (RUI 4.1.1.)

### ISSUE THREAD

**Issue by rakaandro** [RAKWireless/RUI3-Best-Practice#3]
When I compile a ino script, i get an upload-error (compilation is fine):

`Failed uploading: cannot execute upload tool: exec: "C:\\Users\\RaKa\\AppData\\Local\\Arduino15\\packages\\rak_rui\\tools\\uploader\\0.0.0/uploader.exe": file does not exist
`
There is no file in 0.0.0.

When I switch back to 4.1.0 (RAKwireless RUI nRF Boards) it is uploading the firmware without any problems.

Board Manager URL: 
`https://raw.githubusercontent.com/RAKWireless/RAKwireless-Arduino-BSP-Index/staging/RUI_4.1.1_266/package_rakwireless_com_rui_index.json`

System: Windows 11 Pro
Arduino IDE 2.3.2
Board WisBlock Core RAK4631

PS: I am waiting for a comparable API call to "AT+CW" 

Thanks for your work,
Ralf Kramer

**Comment by beegee-tokyo** [comment]
Please try to install the BSP again. It looks like an incomplete installation.

There will be no API calls for the RF test AT commands, as they are intended to be used by test labs.
